spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client:
              clientId: ${CLIENT_ID}
              clientSecret: ${CLIENT_SECRET}
              scope: admin:org
